### ISSUE TITLE
thread 'main' panicked

### ISSUE THREAD

**Issue by jrtSeki** [flukejones/asusctl#47]
When i run 
`rog-control-center`
it shows like
```thread 'main' panicked at rog-control-center/src/main.rs:34:41:
called `Result::unwrap()` on an `Err` value: MethodError(OwnedErrorName("org.freedesktop.DBus.Error.UnknownInterface"), Some("Unknown interface 'org.asuslinux.Platform'"), Msg { type: Error, serial: 5, sender: UniqueName(":1.66"), reply-serial: 5, body: Signature("s"), fds: [] })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```
full is 
```thread 'main' panicked at rog-control-center/src/main.rs:34:41:
called `Result::unwrap()` on an `Err` value: MethodError(OwnedErrorName("org.freedesktop.DBus.Error.UnknownInterface"), Some("Unknown interface 'org.asuslinux.Platform'"), Msg { type: Error, serial: 7, sender: UniqueName(":1.66"), reply-serial: 5, body: Signature("s"), fds: [] })
stack backtrace:
   0:     0x5e9dd4bad729 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h304520fd6a30aa07
   1:     0x5e9dd4406d0b - core::fmt::write::hf5713710ce10ff22
   2:     0x5e9dd4b779a2 - std::io::Write::write_fmt::hda708db57927dacf
   3:     0x5e9dd4bb2188 - std::panicking::default_hook::{{closure}}::he1ad87607d0c11c5
   4:     0x5e9dd4bb3026 - std::panicking::rust_panic_with_hook::had2118629c312a4a
   5:     0x5e9dd4bb2b25 - std::panicking::begin_panic_handler::{{closure}}::h7fa5985d111bafa2
   6:     0x5e9dd4bb2a89 - std::sys::backtrace::__rust_end_short_backtrace::h704d151dbefa09c5
   7:     0x5e9dd4bb2a74 - rust_begin_unwind
   8:     0x5e9dd436bb52 - core::panicking::panic_fmt::h3eea515d05f7a35e
   9:     0x5e9dd436bf35 - core::result::unwrap_failed::h7c8d8bbbcf45dc13
  10:     0x5e9dd43bf8d1 - rog_control_center::main::{{closure}}::h72d5bfed1be6c090
  11:     0x5e9dd43afe79 - rog_control_center::main::h5f944287e9830116
  12:     0x5e9dd43a1883 - std::sys::backtrace::__rust_begin_short_backtrace::h979fb3405f0afa77
  13:     0x5e9dd43c0a74 - main
  14:     0x7d2c9a829d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  15:     0x7d2c9a829e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  16:     0x5e9dd439e1f5 - _start
  17:                0x0 - <unknown>
```

logs:

```sudo journalctl -b -u asusd
[sudo] default 的密码： 
11月 02 17:19:01 default-ROG-Zephyrus-G14-GA403UV-GA403UV systemd[1]: Starting ASUS Notebook Control...
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]: INFO:        daemon v4.3.0
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]: INFO:     rog-anime v1.3.5
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]: INFO:      rog-aura v1.2.0
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]: INFO:      rog-dbus v4.2.0
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]: INFO:  rog-profiles v1.1.3
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]: INFO: rog-supported v4.2.1
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]: INFO: Loaded default LED support data from /etc/asusd/asusd-ledmodes.toml
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]: INFO: Using generic LED control for keyboard brightness only
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]: INFO: Using device at: "/dev/hidraw3" for LED control
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]: INFO:
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]: fan curves kernel interface not found, your laptop does not support this, or the interface is missing.
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]: To enable fan-curve support you require a kernel with the following patch applied:
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]: https://lkml.org/lkml/2021/10/23/250
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]: This patch has been accepted upstream for 5.17 kernel release.
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]: INFO: Product family: ROG Zephyrus G14
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]: INFO: Board name: GA403UV
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]: {
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]:   "anime_ctrl": true,
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]:   "charge_ctrl": {
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]:     "charge_level_set": false
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]:   },
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]:   "platform_profile": {
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]:     "platform_profile": true,
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]:     "fan_curves": false
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]:   },
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]:   "keyboard_led": {
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]:     "prod_id": "19b6",
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]:     "brightness_set": false,
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]:     "stock_led_modes": [],
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]:     "multizone_led_mode": [],
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]:     "per_key_led_mode": false
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]:   },
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]:   "rog_bios_ctrl": {
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]:     "post_sound": false,
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]:     "dedicated_gfx": false,
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]:     "panel_overdrive": false,
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]:     "dgpu_disable": false,
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]:     "egpu_enable": false
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]:   }
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]: }
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]: INFO: G-Sync Switchable Graphics not detected
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]: INFO: If your laptop is not a G-Sync enabled laptop then you can ignore this. Standard graphics switching will still>
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]: INFO: Switch for POST boot sound not detected
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]: ERROR: charge_control: Missing functionality: Charge control not available, you may require a v5.8.10 series kernel >
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]: INFO: Device has profile control available
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]: ERROR: AniMe control: Unsupported AniMe Matrix device found
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]: INFO: Loaded default LED support data from /etc/asusd/asusd-ledmodes.toml
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]: INFO: Using generic LED control for keyboard brightness only
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]: INFO: Using device at: "/dev/hidraw3" for LED control
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]: INFO: Looked for keyboard controller 0x1866: Missing functionality: ASUS LED device node not found
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]: INFO: Looked for keyboard controller 0x1869: Missing functionality: ASUS LED device node not found
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]: INFO: Looked for keyboard controller 0x1854: Missing functionality: ASUS LED device node not found
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]: INFO: Using device at: "/dev/hidraw3" for LED control
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]: INFO: Looked for keyboard controller 0x19b6: Found
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV asusd[1976]: ERROR: Keyboard control: Missing functionality: No brightness control, you may require a v5.11 series kernel or newer
11月 02 17:19:03 default-ROG-Zephyrus-G14-GA403UV-GA403UV systemd[1]: Started ASUS Notebook Control.
```

my system
`Linux version 6.8.0-47-generic (buildd@lcy02-amd64-019) (x86_64-linux-gnu-gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #47~22.04.1-Ubuntu SMP PREEMPT`

product name
`ROG Zephyrus G14`

Thank you

**Comment by flukejones** [comment]
Should not be an issue on latest main

**Comment by jrtSeki** [comment]
Now it looks like: rog-control-center
thread 'main' panicked at rog-control-center/src/main.rs:52:50:
called `Result::unwrap()` on an `Err` value: MethodError(OwnedErrorName("org.freedesktop.DBus.Error.ServiceUnknown"), Some("The name xyz.ljones.Asusd was not provided by any .service files"), Msg { type: Error, serial: 6, sender: UniqueName("org.freedesktop.DBus"), reply-serial: 12, body: Str, fds: [] })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
已中止 (核心已转储)

**Comment by jrtSeki** [comment]
Full message is:
rog-control-center 
thread 'main' panicked at rog-control-center/src/main.rs:52:50:
called `Result::unwrap()` on an `Err` value: MethodError(OwnedErrorName("org.freedesktop.DBus.Error.ServiceUnknown"), Some("The name xyz.ljones.Asusd was not provided by any .service files"), Msg { type: Error, serial: 6, sender: UniqueName("org.freedesktop.DBus"), reply-serial: 12, body: Str, fds: [] })
stack backtrace:
   0:     0x5794bb42721c - <unknown>
   1:     0x5794bac1eae3 - <unknown>
   2:     0x5794bb3f1f62 - <unknown>
   3:     0x5794bb42bec2 - <unknown>
   4:     0x5794bb42bd2b - <unknown>
   5:     0x5794bb42c3c2 - <unknown>
   6:     0x5794bb42bf98 - <unknown>
   7:     0x5794bb42bef9 - <unknown>
   8:     0x5794bb42beec - <unknown>
   9:     0x5794bab3ef3f - <unknown>
  10:     0x5794bab3f2d5 - <unknown>
  11:     0x5794babd28bb - <unknown>
  12:     0x5794babc44dc - <unknown>
  13:     0x5794bab75de3 - <unknown>
  14:     0x5794babd36b0 - <unknown>
  15:     0x73ab5b229d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  16:     0x73ab5b229e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  17:     0x5794bab69ea5 - <unknown>
  18:                0x0 - <unknown>
已中止 (核心已转储)
